version: '3.8'
services:
  simuci-dev:
    build:
      context: ./SimUci
      dockerfile: Dockerfile.dev
    container_name: simuci-dev
    ports:
      - "8000:8000"
      - "5678:5678" # debugpy
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./SimUci/data:/SimUci/data
      - ./SimUci/.env:/SimUci/.env
      - ./SimUci:/SimUci
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - plataforma-atencion-grave

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway-dev
    ports:
      - "8080:8080"
    environment:
      - SIMUCI_MICROSERVICE_URL=http://simuci-dev:8000
    depends_on:
      - simuci-dev
    networks:
      - plataforma-atencion-grave

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   container_name: frontend-dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - api_gateway
  #   networks:
  #     - plataforma-atencion-grave

  mongo:
    image: mongo:7
    container_name: simuci-mongo-dev
    ports:
      - "27017:27017"
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=mongo
      # - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=simuci_db
    volumes:
      - mongo_data_dev:/data/db
    restart: unless-stopped
    networks:
      - plataforma-atencion-grave

volumes:
  mongo_data_dev:

networks:
  plataforma-atencion-grave:
    driver: bridge
