version: '3.8'
services:
  simuci:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simuci-app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped
